language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
before_install:
- openssl aes-256-cbc -K $encrypted_db3cbf257d9f_key -iv $encrypted_db3cbf257d9f_iv
  -in .env.tar.enc -out .env.tar -d
